spring:
  application:
    name: ai-code
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ace_ai_code
    username: root
    password: 12345678
  profiles:
    active: local
  lifecycle:
    timeout-per-shutdown-phase: 60s
server:
  port: 8222
  servlet:
    context-path: /api
  shutdown: graceful
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.ace.aicode.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

